### PR TITLE
README Bullet Point Roles

### PR DESCRIPTION
**Pull request by EndenDragon**
Because Leo was having a hard time using Markdown
(and I think bullets are cool)

### CODE REVIEW

**Comment by LuXeo** [comment]
#weight
<p>wot?</p>

**Comment by LuXeo** [comment]
### Oh that was Jed, not me

**Comment by LuXeo** [comment]
fixed :balance_scale:

**Comment by EndenDragon** [comment]
Kek markdown *is* annoying ik that feel when I'm learning it before

**Pull request closed without merging**
